[tool.poetry]
name = "rag-practice"
version = "0.1.0"
description = ""
authors = ["eunv0110 <eunvv0110@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ipykernel = "^6.30.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
